### ISSUE TITLE
Doesn't minify reliably 

### ISSUE THREAD

**Issue by heyheyjc** [DVLP/localStorageDB#1]
The properties .v and .k should be specified as ['v'] and ['k'] and {'k': '', 'v': ''} to protect against mangling, as should anything that is stored in any persistent storage. As is, it creates subtle incompatibilities between versions where they may be mangled differently. (Nice functionality overall, thanks)

**Comment by azzok** [comment]
I got following error

index.html:152 Uncaught TypeError: Cannot read property 'transaction' of undefined

**Comment by gruelas16** [comment]
Same here, did you @heyheyjc find a solution for it ??

**Comment by DVLP** [comment]
Fixed, also now available through NPM as `npm i localdata`
