### ISSUE TITLE
ESM compatibility for NPM-based install?

### ISSUE THREAD

**Issue by blakehurd** [DVLP/localStorageDB#10]
First off, thanks for the handy script! I've been using it already; quite useful for my purposes.

When I was translating one of my projects from vanilla JS in browser to vanilla TS with Vite, I ran into issues trying to switch this to use via npm using the README instructions.

Specifically getting this error "Could not find a declaration file for module 'localdata'. "

I found I could just port the .js snippet into my project, name it *.mjs and slap an "export default ldb;" on the end and that works, but I was hoping that the npm-based route would work for me. Any thoughts or plans on supporting this?

Thanks in advance.

**Comment by DVLP** [comment]
I'm glad you find this useful. Feel free to make any PRs to support i.e. TypeScript and I'll review it

**Comment by blakehurd** [comment]
Opened https://github.com/DVLP/localStorageDB/pull/11.

Re: testing, I added that file locally to the corresponding node_module for localdata and it seems to resolve for me without requiring me to copy it locally as an .mjs. No modifications needed to the README AFAICT.

**Comment by ThisIsVegas** [comment]
Thank you @blakehurd for the declaration file! But I encountered an issue on my end.

The declaration file caused an error `TS1183: implementation cannot be declared in ambient context` when using this library in a TypeScript project and caused a build error when building the project with Webpack.

I opened #13 which forwarded changes from #11

**Comment by DVLP** [comment]
Thanks @blakehurd and @ThisIsVegas This is now merged and updated in npm as 0.1.4
