### ISSUE TITLE
You should remove the setTimeout

### ISSUE THREAD

**Issue by dvhx** [DVLP/localStorageDB#2]
Wrap the code where you creating db into function like this:
  function foo(callback) {
    ...
  }

In the getValue if !db simply call that function (instead of waiting in timer loop):

function getValue(key, callback) {
    if(!db) {
      foo(function () {
        if(!db) {
          throw "some error";
        }
        getValue(key, callback);
      };
      return;
    }
  ...

**Comment by DVLP** [comment]
@dvhx that would create a maximum stack size exceeded error and/or slow down a loading app. I think registering to an event would be an optimal solution. Some kind of queue to be resolved  when db is ready. For now this crude debounce mechanism should be enough and it's only executed once, milliseconds after the page loads so will do until some major refactor will be happening
