### ISSUE TITLE
I got error 'transaction' of undefined while using this script

### ISSUE THREAD

**Issue by azzok** [DVLP/localStorageDB#4]
I got following issue when running localStorageDB script

**index.html:152 Uncaught TypeError: Cannot read property 'transaction' of undefined**

**Comment by gruelas16** [comment]
Same here, did you @azzok  find a solution for it ??

**Comment by cyberflow911** [comment]
!function(){var e=window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB;if(e){var t,n={k:"",v:""},o=e.open("d2",1);o.onsuccess=function(e){t=this.result},o.onerror=function(e){console.error("indexedDB request error"),console.log(e)},o.onupgradeneeded=function(e){t=null,e.target.result.createObjectStore("s",{keyPath:"k"}).transaction.oncomplete=function(e){t=e.target.db}},window.ldb={get:function e(n,o){return t?void(t.transaction("s").objectStore("s").get(n).onsuccess=function(e){var t=e.target.result&&e.target.result.v||null;o(t)}):void setTimeout(function(){e(n,o)},100)},set:function(e,o){!function e(o,r){n.k=o,n.v=r,t?t.transaction("s","readwrite").objectStore("s").put(n):setTimeout(()=>e(o,r),100)}(e,o)}}}else console.error("indexDB not supported")}();


try this script it will resolve your issue
@DVLP @azzok

**Comment by DVLP** [comment]
Thanks @cyberflow911 
Applied a similar fix in the new version

**Comment by azzok** [comment]
@DVLP Thankyou, I will check
